services:
  - type: web
    name: music-dashboard
    region: frankfurt
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir src  --timeout=0 --workers=6 --threads=6 main:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
