services:
  - type: web
    name: music-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir src main:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
